dnt/authapp/urls.py
from django.urls import path
import authapp.views as auth

app_name = 'authapp'

urlpatterns = [
    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('register/', auth.register, name='register'),
    path('edit/', auth.edit, name='edit'),
]

dnt/dnt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from main import views as main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', main.index, name='home'),  # todo
                  # path('index/', main.index, name="home"),
                  path('authapp/', include('authapp.urls', namespace='auth')),
                  path('chat/', include('chat.urls', namespace='chat')),
                  path('custom_admin/', include('custom_admin.urls', namespace='custom_admin')),
                  path('games/', include('games.urls', namespace='games')),
                  path('quest/', include('questions.urls', namespace='quest')),
                  path('telegram/', include('telegram.urls', namespace='telegram')),
                  path('user_profile/', include('user_profile.urls', namespace='user_profile')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dnt/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator
from games.models import Lobby, Game
from questions.models import Question

NULLABLE = {"blank": True, "null": True}


class AuthUser(AbstractUser):

    RANKS = (
        ('iron', 'Железо'),
        ('bronze', 'Бронза'),
        ('silver', 'Серебро'),
        ('gold', 'Золото'),
        ('platinum', 'Платина'),
        ('diamond', 'Алмаз'),
        ('master', 'Мастер'),
        ('grandmaster', 'Грандмастер'),
        ('challenger', 'Претендент')
    )

    nickname = models.CharField(max_length=16, verbose_name='Ник')
    telegram_id = models.PositiveIntegerField(verbose_name='ID Телеграм', **NULLABLE)
    email = models.EmailField(verbose_name='email', **NULLABLE)
    birthdate = models.DateField(verbose_name='Дата рождения', null=True)
    is_moderator = models.BooleanField(default=False, verbose_name='Модератор')
    level = models.PositiveSmallIntegerField(default=1, verbose_name='Уровень')
    current_experience = models.PositiveSmallIntegerField(default=0, verbose_name='Опыт текущего уровня')
    rank = models.CharField(choices=RANKS, default=RANKS[0], max_length=16, verbose_name='Ранг')
    division = models.PositiveSmallIntegerField(default=4, verbose_name='Дивизион', validators=[
            MaxValueValidator(4),
            MinValueValidator(1)
        ])
    current_lp = models.PositiveSmallIntegerField(default=0, verbose_name='Текущие ранговые очки')
    friends = models.ManyToManyField('self', verbose_name='Друзья')
    current_lobby = models.ForeignKey(Lobby, related_name='players', on_delete=models.SET_NULL, **NULLABLE)
    is_lobby_leader = models.BooleanField(default=False)
    current_game = models.ForeignKey(Game, on_delete=models.SET_NULL, null=True, blank=True)
    avatar = models.ImageField(upload_to="users", verbose_name=_("Аватар"), **NULLABLE)

    @property
    def get_friends(self):
        return AuthUser.objects.filter(pk__in=self.friends.values_list('pk'))


class QuestionRatedByUser(models.Model):
    """
    Модель для связи вопроса с пользователем.
    Каждая запись - факт оценки вопроса пользователем.
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос')
    user = models.ForeignKey(AuthUser, on_delete=models.CASCADE, verbose_name='Пользователь')

    class Meta:
        unique_together = ('question', 'user',)


class Remark(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос')
    text = models.CharField(max_length=128, verbose_name='Замечание')
    author = models.ForeignKey(AuthUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    rating = models.IntegerField(default=0, verbose_name='Очки')

    class Meta:
        unique_together = ('question', 'author',)

    def __str__(self):
        return f'#{self.text} {self.rating}'

dnt/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import AuthUser


class AuthUserLoginForm(AuthenticationForm):

    class Meta:
        model = AuthUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class AuthUserRegisterForm(UserCreationForm):

    class Meta:
        model = AuthUser
        fields = ('username', 'nickname', 'birthdate', 'email', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class AuthUserEditForm(UserChangeForm):
    class Meta:
        model = AuthUser
        fields = ('username', 'nickname', 'birthdate', 'email', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

dnt/authapp/views.py
from django.shortcuts import render
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from authapp.forms import AuthUserRegisterForm, AuthUserLoginForm, AuthUserEditForm


def login(request):
    login_form = AuthUserLoginForm(data=request.POST)
    if 'next' in request.GET.keys():
        next_value = request.GET['next']
    else:
        next_value = ''
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('home'))
    context = {
        'title': 'Вход',
        'login_form': login_form,
        'next': next_value
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('auth:login'))


def register(request):
    if request.method == 'POST':
        register_form = AuthUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('home'))
    else:
        register_form = AuthUserRegisterForm()

    context = {
        'title': 'Регистрация',
        'register_form': register_form,
    }
    return render(request, 'authapp/register.html', context)


@login_required
def edit(request):
    if request.method == 'POST':
        edit_form = AuthUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('home'))
    else:
        edit_form = AuthUserEditForm(instance=request.user)

    context = {
        'title': 'edit',
        'edit_form': edit_form,
    }
    return render(request, 'authapp/edit.html', context)

dnt/authapp/templates/authapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title|title }}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>

<body>
    <div class="container_auth">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

dnt/authapp/templates/authapp/edit.html
{% extends 'main/base.html' %}

{% block title %}
    Редактировать профиль
{% endblock %}

{% block body %}
<form action="{% url 'auth:edit' %}" class="form_settings" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="auth_h1">Редактировать профиль</h1>
    {% for field in edit_form %}
    <div class="field_wrapper">
        {% if field.label != "Password" %}
        <p><span>{{ field.label_tag }}</span>{{ field }}</p>{{ field.errors }}
        {% endif %}
    </div>
    {% endfor %}
    {% for field in edit_profile_form %}
    <div class="field_wrapper">
        {{ field.label_tag }}{{ field }}{{ field.errors }}
    </div>
    {% endfor %}
    <div class="container-buttons">
        <input class="submit" type="submit" value="Сохранить">
    </div>
</form>
{% endblock %}

dnt/authapp/templates/authapp/login.html
{% extends "main/base.html" %}

{% block title %}
    {{ title|title }}
{% endblock %}

{% block body %}
    <form action="{% url 'auth:login' %}" class="form_settings" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {% for field in login_form %}
            <p><span>{{ field.label_tag }}</span>{{ field }}</p>
        {% endfor %}
        <div class="container-buttons">
            <a href="{% url 'authapp:register' %}" class="submit">Регистрация</a>
            <input class="submit" type="submit" value="Вход">
        </div>
    </form>
{% endblock %}

dnt/authapp/templates/authapp/register.html
{% extends "main/base.html" %}

{% block title %}
    {{ title|title }}
{% endblock %}

{% block body %}
    <form action="{% url 'auth:register' %}" class="form_settings" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in register_form %}
        <p><span>{{ field.label_tag }}</span>{{ field }}</p>{{ field.errors }}
        {% endfor %}
        <div class="container-buttons">
            <a href="{% url 'authapp:login' %}" class="submit">Вход</a>
            <input class="submit" type="submit" value="Регистрация">
        </div>
    </form>
{% endblock %}