dnt/authapp/urls.py
from django.urls import path
import authapp.views as auth

app_name = 'authapp'

urlpatterns = [
    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('register/', auth.register, name='register'),
    path('edit/', auth.edit, name='edit'),
]

dnt/dnt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from main import views as main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', main.index, name='home'),  # todo
                  # path('index/', main.index, name="home"),
                  path('authapp/', include('authapp.urls', namespace='auth')),
                  path('chat/', include('chat.urls', namespace='chat')),
                  path('custom_admin/', include('custom_admin.urls', namespace='custom_admin')),
                  path('games/', include('games.urls', namespace='games')),
                  path('quest/', include('questions.urls', namespace='quest')),
                  path('telegram/', include('telegram.urls', namespace='telegram')),
                  path('user_profile/', include('user_profile.urls', namespace='user_profile')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dnt/games/urls.py
from django.urls import path
import games.views as games

app_name = 'games'

urlpatterns = [
    path('lobby/', games.create_lobby, name='lobby'),
    path('join_lobby/', games.join_lobby, name='join_lobby'),
    path('join_lobby_ajax/', games.join_lobby_ajax, name='join_lobby_ajax'),
    path('change_game_mode/', games.change_game_mode, name='change_game_mode'),
    path('queue/', games.queue, name='queue'),
    path('quit_lobby/', games.quit_lobby, name='quit_lobby'),
    path('cancel_queue/', games.cancel_queue, name='cancel_queue'),
    path('create_game/', games.create_game, name='create_game'),
    path('game/', games.game, name='game'),
    path('start_game/', games.start_game, name='start_game'),
    path('check_answer/', games.check_answer, name='check_answer'),
    path('results/<int:game_id>/', games.results, name='results'),
]

dnt/questions/urls.py
from django.urls import path
from questions import views

app_name = 'questions'

urlpatterns = [
    path('', views.QuestionView.as_view(), name='quest'),
    path('add_quest/', views.AddQuestionsView.as_view(), name='add_quest'),
    path('<int:pk>/delete_quest/', views.QuestionDeleteView.as_view(), name='delete_quest'),
    path('<int:pk>/update_quest/', views.QuestionUpdateView.as_view(), name='update_quest'),
    path('grade_quest/', views.GradeQuestionView.as_view(), name='grade_quest'),
    path('offer_quest/', views.OfferQuestionView.as_view(), name='offer_quest'),
]

dnt/user_profile/urls.py
from django.urls import path
import user_profile.views as u_p

app_name = 'user_profile'

urlpatterns = [
    path('', u_p.index, name='index'),
    path('friends/', u_p.view_friends, name='friends'),
    path('users/<int:pk>/', u_p.UserDetailView.as_view(), name='profile'),
    path('games_list/', u_p.my_games, name='games_list'),
    path('search_friends/', u_p.manage_friends, name='search_friends'),
    path('leaderboard/', u_p.leaderboard, name='leaderboard'),
]

dnt/main/models.py
from django.db import models

# Create your models here.

dnt/main/views.py
from django.shortcuts import render


def index(request):
    context = {
        'title': 'Home',
    }
    return render(request, 'main/index.html', context=context)

dnt/main/templates/main/includes/footer.html
<div id="content_footer"></div>
    <div id="footer">
        Copyright &copy; Geek_Project {{ date }}
    </div>
</div>

dnt/main/templates/main/includes/head.html
<div id="main">
    <div id="header">
        <div id="logo">
            <div id="logo_text">
                <h1><a href="/">крутые<span class="logo_colour">перцы</span></a></h1>
                <h2>Викторины. Игры. Соревнования.</h2>
            </div>
        </div>
        <div id="delimiter">
            {% if not request.user.is_authenticated %}
            <a href="{% url 'auth:login' %}">Войти</a>
            <a href="{% url 'auth:register' %}">Зарегистрироваться</a>
            {% else %}
            <a href="{% url 'auth:logout' %}">Выйти</a>
            <a href="{% url 'user_profile:profile' pk=user.pk %}">Просмотр профиля</a>
            <a href="{% url 'auth:edit' %}">Редактировать профиль</a>
            {% endif %}
            {% if request.user.is_authenticated and request.user.current_game %}
            <a href="{% url 'games:game' %}">Продолжить игру</a>
            {% elif request.user.is_authenticated %}
            <a href="{% url 'games:lobby' %}">Играть</a>
            {% endif %}
            {% if request.user.is_moderator %}
            <a href="{% url 'quest:quest' %}">Модерация вопросов</a>
            <a href="{% url 'quest:add_quest' %}">Добавить вопрос</a>
            {% elif request.user.is_authenticated %}
            <a href="{% url 'quest:grade_quest' %}">Оценка вопросов</a>
            <a href="{% url 'quest:offer_quest' %}">Предложить вопрос</a>
            {% endif %}
        </div>
    </div>
</div>

dnt/main/templates/main/includes/header.html
{% load static %}

<div id="main">
    <div id="header">
        <div id="logo">
            <div id="logo_text">
                <h1><a href="/">крутые<span class="logo_colour">перцы</span></a></h1>
                <h2>Викторины. Игры. Соревнования.</h2>
            </div>
        </div>
            <div id="delimiter">
                {% if request.resolver_match.url_name != 'game' %}
                    <div class="lobby_invitation_block">
                        <span class="lobby_invitation_nickname"></span>
                        <span class="lobby_invitation_accept">Принять</span>
                        <span class="lobby_invitation_reject">Отклонить</span>
                    </div>
                    {% if not request.user.is_authenticated %}
                    <a href="{% url 'auth:login' %}">Войти</a>
                    <a href="{% url 'auth:register' %}">Зарегистрироваться</a>
                    {% else %}
                    <a href="{% url 'auth:logout' %}">Выйти</a>
                    <a href="{% url 'user_profile:profile' pk=user.pk %}">Просмотр профиля</a>
                    {% endif %}
                    {% if request.user.is_authenticated and request.user.current_game %}
                    <a href="{% url 'games:game' %}">Продолжить игру</a>
                    {% elif request.user.is_authenticated %}
                    <a href="{% url 'games:lobby' %}">Играть</a>
                    <div class="header_friends_button">
                        Друзья
                        <div class="header_friends_block">
                            <a href="{% url 'user_profile:search_friends' %}" class="header_friends_add">Добавить друга</a>
                            {% for friend in request.user.get_friends %}
                            <div class="header_friend">{{ friend.nickname }}
                                <div class="header_friend_icons"><img src="{% static 'img/chat_open_icon.png' %}" alt="chat" class="header_friend_icon header_friend_chat" id="chat_friend_{{ friend.pk }}">
                                <img src="{% static 'img/invite_icon.webp' %}" alt="invite" class="header_friend_icon header_friend_invite" id="invite_friend_{{ friend.pk }}"></div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    {% if request.user.is_moderator %}
                    <a href="{% url 'quest:quest' %}">Модерация вопросов</a>
                    <a href="{% url 'quest:add_quest' %}">Добавить вопрос</a>
                    {% elif request.user.is_authenticated %}
                    <a href="{% url 'quest:grade_quest' %}">Оценка вопросов</a>
                    <a href="{% url 'quest:offer_quest' %}">Предложить вопрос</a>
                    {% endif %}
                {% else %}
                    Приятной игры!
                {% endif %}
            </div>
    </div>
</div>

dnt/main/templates/main/includes/inc-info.html
<div class="sidebar">
    <p></p>
    {% if not request.user.is_authenticated %}
    <p>
        У Вас уже есть аккаунт и Вы хотите продолжить игру?
        <h4><a href="{% url 'auth:login' %}">Войти</a></h4>
    </p>
    <p>
        Пройдите регистрацию, это не займёт много времени. Вы сможете предлагать свои вопросы для викторин и играть с друзьями.
        <h4><a href="{% url 'auth:register' %}">Регистрация</a></h4>
    </p>
    {% endif %}
</div>