dnt/dnt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from main import views as main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', main.index, name='home'),  # todo
                  # path('index/', main.index, name="home"),
                  path('authapp/', include('authapp.urls', namespace='auth')),
                  path('chat/', include('chat.urls', namespace='chat')),
                  path('custom_admin/', include('custom_admin.urls', namespace='custom_admin')),
                  path('games/', include('games.urls', namespace='games')),
                  path('quest/', include('questions.urls', namespace='quest')),
                  path('telegram/', include('telegram.urls', namespace='telegram')),
                  path('user_profile/', include('user_profile.urls', namespace='user_profile')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dnt/questions/urls.py
from django.urls import path
from questions import views

app_name = 'questions'

urlpatterns = [
    path('', views.QuestionView.as_view(), name='quest'),
    path('add_quest/', views.AddQuestionsView.as_view(), name='add_quest'),
    path('<int:pk>/delete_quest/', views.QuestionDeleteView.as_view(), name='delete_quest'),
    path('<int:pk>/update_quest/', views.QuestionUpdateView.as_view(), name='update_quest'),
    path('grade_quest/', views.GradeQuestionView.as_view(), name='grade_quest'),
    path('offer_quest/', views.OfferQuestionView.as_view(), name='offer_quest'),
]

dnt/questions/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=64, verbose_name='Категория')

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name}'


class Type(models.Model):
    name = models.CharField(max_length=64, verbose_name='Тип')

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name}'


class SubType(models.Model):
    name = models.CharField(max_length=64, verbose_name='Подтип')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, related_name='subtypes', verbose_name='Тип')

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name}'


class Answer(models.Model):
    answer = models.CharField(max_length=64, verbose_name='Ответ')
    subtype = models.ForeignKey(SubType, on_delete=models.CASCADE, verbose_name='Подтип')
    is_validated = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.answer}'


class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Тема вопроса')
    question = models.CharField(max_length=128, verbose_name='Вопрос')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, verbose_name='Правильный ответ')
    is_validated = models.BooleanField(default=False, verbose_name='Одобрен')
    rating = models.IntegerField(default=0, verbose_name='Очки')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.question}'


class QuestionComplaint(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос')
    text = models.CharField(max_length=128, verbose_name='Жалоба')

    def __str__(self):
        return f'{self.text}'

dnt/questions/views.py
from django.contrib import messages
from django.core.cache import cache
from django.db.models import Q, Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, DeleteView, UpdateView, CreateView, DetailView

from authapp.models import Remark, AuthUser, QuestionRatedByUser
from questions.models import Question, Category, Type, SubType, Answer, QuestionComplaint

from variables import *


class QuestionView(TemplateView):
    template_name = 'questions/qes_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Question.objects.all()
        context_data['complaints'] = QuestionComplaint.objects.filter()
        return context_data

    def post(self, request, *args, **kwargs):
        if all(
                (
                        request.POST.get('question_id'),
                        request.POST.get('complaint'),
                )
        ):
            print(request.POST)
            new_complaint = QuestionComplaint.objects.create(
                question=Question.objects.get(pk=int(request.POST.get('question_id'))),
                text=request.POST.get('complaint')
            )
            new_complaint.save()
            messages.add_message(request, messages.INFO, 'Замечание добавлено')
            return HttpResponseRedirect(reverse('quest:quest'))
        else:
            messages.add_message(
                request, messages.WARNING,
                'Не удалось добавить замечание'
            )
            return HttpResponseRedirect(reverse('quest:quest'))


class QuestionDeleteView(DeleteView):
    model = Question
    success_url = reverse_lazy('quest:quest')


class QuestionUpdateView(UpdateView):
    model = Question
    fields = ('question', 'is_validated')
    success_url = reverse_lazy('quest:quest')


class AddQuestionsView(TemplateView):
    template_name = 'questions/add_quest.html'

    def post(self, request, *args, **kwargs):
        try:
            if all(
                    (
                            request.POST.get('question'),
                            request.POST.get('category'),
                            request.POST.get('type'),
                            request.POST.get('subtype'),
                            request.POST.get('answer'),
                    )
            ):
                new_category = Category.objects.create(
                    name=request.POST.get('category')
                )
                new_category.save()
                new_type = Type.objects.create(
                    name=request.POST.get('type')
                )
                new_type.save()
                new_subtype = SubType.objects.create(
                    name=request.POST.get('subtype'),
                    type=Type.objects.get(name=request.POST.get('type'))
                )
                new_subtype.save()
                new_answer = Answer.objects.create(
                    answer=request.POST.get('answer'),
                    subtype=SubType.objects.get(name=request.POST.get('subtype'))
                )
                new_answer.save()
                new_quest = Question.objects.create(
                    category=Category.objects.get(name=request.POST.get('category')),
                    question=request.POST.get('question'),
                    answer=Answer.objects.get(answer=request.POST.get('answer')),
                )
                new_quest.save()
                messages.add_message(request, messages.INFO, 'Вопрос добавлен успешно')
                return HttpResponseRedirect(reverse('quest:add_quest'))
            else:
                messages.add_message(
                    request, messages.WARNING,
                    'Не удалось добавить вопрос'
                )
                return HttpResponseRedirect(reverse('quest:add_quest'))
        except Exception as ex:
            messages.add_message(
                request, messages.WARNING,
                'Не удалось добавить вопрос'
            )
            return HttpResponseRedirect(reverse('quest:add_quest'))


class GradeQuestionView(TemplateView):
    template_name = 'questions/grade_quest.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['question_list'] = Question.objects.filter(~Q(pk__in=[x.question.pk for x in Remark.objects.filter(author=self.request.user)]) &
                                                                Q(is_validated=False)).order_by('?').first()
        context_data['remark_list'] = Remark.objects.filter(question=context_data['question_list'])
        return context_data

    def post(self, request, *args, **kwargs):
        try:
            if all(
                    (
                            request.POST.get('question'),
                            request.POST.get('text'),
                            request.POST.get('author'),
                            request.POST.get('rating')
                    )
            ):
                new_remark = Remark.objects.create(
                    question=Question.objects.get(question=request.POST.get('question')),
                    text=request.POST.get('text'),
                    author=AuthUser.objects.get(username=request.POST.get('author')),
                    rating=request.POST.get('rating'),
                )
                new_remark.save()
                question = Question.objects.get(question=request.POST.get('question'))
                remark = Remark.objects.filter(question=question).aggregate(Sum('rating'))
                if remark['rating__sum'] >= VOTES:
                    question.is_validated = True
                    question.save()
                    question.answer.is_validated = True
                    question.answer.save()
                elif remark['rating__sum'] <= -VOTES:
                    question.delete()
                messages.add_message(request, messages.INFO, 'Оценка выполнена')
                return HttpResponseRedirect(reverse('quest:grade_quest'))
            else:
                messages.add_message(
                    request, messages.WARNING,
                    'Не удалось выполнить оценку'
                )
                return HttpResponseRedirect(reverse('quest:grade_quest'))
        except Exception as ex:
            messages.add_message(
                request, messages.WARNING,
                'Не удалось выполнить оценку'
            )
            return HttpResponseRedirect(reverse('quest:grade_quest'))


class OfferQuestionView(TemplateView):
    template_name = 'questions/offer_quest.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['type_list'] = Type.objects.all()
        context_data['subtype_list'] = SubType.objects.all()
        context_data['category_list'] = Category.objects.all()

        return context_data

    def post(self, request, *args, **kwargs):
        try:
            if all(
                    (
                            request.POST.get('question'),
                            request.POST.get('category'),
                            request.POST.get('type'),
                            request.POST.get('subtype'),
                            request.POST.get('answer'),
                    )
            ):
                new_answer = Answer.objects.create(
                    answer=request.POST.get('answer'),
                    subtype=SubType.objects.get(name=request.POST.get('subtype'))
                )
                new_answer.save()
                new_quest = Question.objects.create(
                    category=Category.objects.get(name=request.POST.get('category')),
                    question=request.POST.get('question'),
                    answer=new_answer,
                )
                new_quest.save()
                messages.add_message(request, messages.INFO, 'Вопрос добавлен успешно')
                return HttpResponseRedirect(reverse('quest:offer_quest'))
            else:
                messages.add_message(
                    request, messages.WARNING,
                    'Не удалось добавить вопрос'
                )
                return HttpResponseRedirect(reverse('quest:offer_quest'))
        except Exception as ex:
            messages.add_message(
                request, messages.WARNING,
                'Не удалось добавить вопрос'
            )
            return HttpResponseRedirect(reverse('quest:offer_quest'))

dnt/questions/templates/questions/add_quest.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Добавить вопрос
{% endblock %}

{% block body %}
    {% include 'questions/includes/messages.html' %}
    <h1>Добавить вопрос</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                <input type="text" name="question" autofocus=""
                       autocapitalize="none" autocomplete="question"
                       maxlength="150" class="textinput textInput form-control"
                       required="" id="id_question" placeholder="Вопрос">
            </p>
            <p>
                <input type="text" name="category" autofocus=""
                       autocapitalize="none" autocomplete="category"
                       maxlength="150" class="textinput textInput form-control"
                       required="" id="id_category" placeholder="Категория">
            </p>
                    <p>
                <input type="text" name="type" autofocus=""
                       autocapitalize="none" autocomplete="type"
                       maxlength="150" class="textinput textInput form-control"
                       required="" id="id_type" placeholder="Тип">
            </p>
            <p>
                <input type="text" name="subtype" autofocus=""
                       autocapitalize="none" autocomplete="subtype"
                       maxlength="150" class="textinput textInput form-control"
                       required="" id="id_subtype" placeholder="Подтип">
            </p>
            <p>
                <input type="text" name="answer" autofocus=""
                       autocapitalize="none" autocomplete="answer"
                       maxlength="150" class="textinput textInput form-control"
                       required="" id="id_answer" placeholder="Ответ">
            </p>
            <p>
                <button type="submit" class="btn btn-primary btn-block">
                    Добавить
                </button>
            </p>
        </form>
    {% block js %}
    <script>
            $(document).ready(function () {
                {% if messages %}
                    // Toasts
                    $(".toast").toast({ delay: 5000 });
                    $(".toast").toast("show");
                {% endif %}
            });

    </script>
    {% endblock %}
{% endblock %}

dnt/questions/templates/questions/grade_quest.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Оценка вопросов
{% endblock %}

{% block body %}
    {% include 'questions/includes/messages.html' %}
    <h1>Оценить вопрос</h1>
    {% if question_list.question != None %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                    <input type="hidden" name="question" value="{{ question_list.question }}">Вопрос: {{ question_list.question }}
            </p>
            <p>
                    Категория вопроса: {{ question_list.category }}
            </p>
            <p>
                    Ответ: {{ question_list.answer }} ({{ question_list.answer.subtype.type }}, {{ question_list.answer.subtype }})
            </p>
            <p>
                <input type="text" name="text" autofocus=""
                       autocapitalize="none" autocomplete="text"
                       maxlength="150" class="textinput textInput form-control"
                       required="" id="id_text" value="Без замечаний" placeholder="Замечание">
            </p>
            <p>
                <input type="hidden" name="author" value="{{ request.user.username }}">
            </p>
            <p>
                <button type="submit" class="btn btn-default" name="rating" value="1">
                    👍
                </button>
                <button type="submit" class="btn btn-default" name="rating" value="-1">
                    👎
                </button>
            </p>
        </form>
    {% else %}
    <h2> Вы оценили все вопросы</h2>
    {% endif %}
    <h3> Отзывы пользователей</h3>
            {% for item in remark_list %}
                    <p>{{ item.author }}
                        {{ item.text }}
                        {{ item.rating }}</p>
            {% endfor %}
    {% block js %}
    <script>
            $(document).ready(function () {
                {% if messages %}
                    // Toasts
                    $(".toast").toast({ delay: 5000 });
                    $(".toast").toast("show");
                {% endif %}
            });


    </script>
    {% endblock %}
{% endblock %}

dnt/questions/templates/questions/offer_quest.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Предложить вопрос
{% endblock %}

{% block body %}
    {% include 'questions/includes/messages.html' %}
        <h1>Предложить вопрос</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    <input type="text" name="question" autofocus=""
                           autocapitalize="none" autocomplete="question"
                           maxlength="150" class="textinput textInput form-control"
                           required="" id="id_question" placeholder="Вопрос">
                </p>
                <p>
                    Категория:
                    <select name="category" required="" id="id_category">
                        {% for item in category_list %}
                        <option value="{{ item.name }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p>
                    Тип:
                    <select name="type" required="" id="id_type">
                        {% for item in type_list %}
                        <option value="{{ item.name }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p>
                    Подтип:
                    <select name="subtype" required="" id="id_subtype">
                        {% for item in subtype_list %}
                        <option value="{{ item.name }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p>
                    <input type="text" name="answer" autofocus=""
                           autocapitalize="none" autocomplete="answer"
                           maxlength="150" class="textinput textInput form-control"
                           required="" id="id_answer" placeholder="Ответ">
                </p>
                <p>
                    <button type="submit" class="btn btn-primary btn-block">
                        Предложить
                    </button>
                </p>
            </form>
        {% block js %}
        <script>
                $(document).ready(function () {
                    {% if messages %}
                        // Toasts
                        $(".toast").toast({ delay: 5000 });
                        $(".toast").toast("show");
                    {% endif %}
                });


        </script>
        {% endblock %}
{% endblock %}

dnt/questions/templates/questions/qes_list.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Модерация вопросов
{% endblock %}

{% block body %}
    <h1>Модерация вопросов</h1>
        {% for item in object_list %}
            {% if item.is_validated == False %}
                <div>
                    <h2>Категория вопроса: {{ item.category.name }}</h2>
                    <h3>{{ item.created_at }}</h3>
                    <p>Вопрос: {{ item.question }}</p>
                    <p>Ответ: {{ item.answer }}</p>
                    <p>Тип: {{ item.answer.subtype.type }}</p>
                    <p>Подтип: {{ item.answer.subtype }}</p>
                    <a href="{% url 'quest:update_quest' pk=item.pk %}">Одобрить</a>
                    <a href="{% url 'quest:delete_quest' pk=item.pk %}">Не одобрять</a>
                </div>
            {% endif %}
        {% endfor %}
{% endblock %}

dnt/questions/templates/questions/question_confirm_delete.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Удалить вопрос
{% endblock %}

{% block body %}
    <div class="row justify-content-center pt-3">
        <div class="col-md-8 col-lg-6">
            <h2>Удалить вопрос?</h2>
            <p>
                Удалить вопрос:<br>
                "{{ object.question }}" от {{ object.created_at }}
            </p>
            <p>
            <div class="row">
                <div class="col-6">

                    <form action="{% url 'quest:delete_quest' pk=object.pk %}"
                          method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-block"
                                type="submit">Подтвердить
                        </button>
                    </form>
                </div>
                <div class="col-6">
                    <a class="btn btn-primary btn-block" href="{% url 'quest:quest' %}"
                       role="button">Отмена</a>
                </div>
            </div>
            </p>
        </div>
    </div>
{% endblock %}

dnt/questions/templates/questions/question_form.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Подтверждение добавления
{% endblock %}

{% block body %}
    <div class="row justify-content-center pt-3">
        <div class="col-md-12 col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-primary btn-block">Опубликовать</button>
            </form>
        </div>
    </div>
{% endblock %}