dnt/authapp/urls.py
from django.urls import path
import authapp.views as auth

app_name = 'authapp'

urlpatterns = [
    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('register/', auth.register, name='register'),
    path('edit/', auth.edit, name='edit'),
]

dnt/dnt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from main import views as main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', main.index, name='home'),  # todo
                  # path('index/', main.index, name="home"),
                  path('authapp/', include('authapp.urls', namespace='auth')),
                  path('chat/', include('chat.urls', namespace='chat')),
                  path('custom_admin/', include('custom_admin.urls', namespace='custom_admin')),
                  path('games/', include('games.urls', namespace='games')),
                  path('quest/', include('questions.urls', namespace='quest')),
                  path('telegram/', include('telegram.urls', namespace='telegram')),
                  path('user_profile/', include('user_profile.urls', namespace='user_profile')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dnt/user_profile/urls.py
from django.urls import path
import user_profile.views as u_p

app_name = 'user_profile'

urlpatterns = [
    path('', u_p.index, name='index'),
    path('friends/', u_p.view_friends, name='friends'),
    path('users/<int:pk>/', u_p.UserDetailView.as_view(), name='profile'),
    path('games_list/', u_p.my_games, name='games_list'),
    path('search_friends/', u_p.manage_friends, name='search_friends'),
    path('leaderboard/', u_p.leaderboard, name='leaderboard'),
]

dnt/user_profile/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from authapp.models import AuthUser
from games.models import Game


def index(request):
    pass


@login_required
def user_list(request):
    users = AuthUser.objects.all()
    context = {
        'users': users,
    }
    return render(request, 'user_profile/user_list.html', context)


@login_required
def view_friends(request):
    user = AuthUser.objects.get(username=request.user)
    friends = user.friends.all()
    context = {
        'friends': friends,
    }
    return render(request, 'user_profile/friends.html', context)


class UserDetailView(DetailView):
    model = AuthUser
    template_name = 'user_profile/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = AuthUser.objects.get(pk=self.kwargs['pk'])

        return context


@login_required
def manage_friends(request):
    user = request.user
    query = request.GET.get('q')
    action = request.POST.get('action')
    friend_username = request.POST.get('friend_username')

    if query:
        results = AuthUser.objects.filter(username__icontains=query).exclude(username=user)
    else:
        results = None

    if action == 'add':
        friend = get_object_or_404(AuthUser, username=friend_username)
        if friend == request.user:
            messages.error(request, "Вы не можете добавить себя в друзья")
        else:
            user.friends.add(friend)
    elif action == 'remove':
        friend = get_object_or_404(user.friends, username=friend_username)
        user.friends.remove(friend)

    context = {
        'user': user,
        'results': results,
    }
    return render(request, 'user_profile/manage_friends.html', context)


# @login_required
# def my_games(request):
#     user = request.user
#     objs = Game.objects.filter(players=user).order_by('-started')  # all() == filter(players=user).order_by('-started')
#     games = [x for x in objs if str(user.pk) in x.players]
#     context = {
#         'user': user,
#         'games': games,
#     }
#     return render(request, 'user_profile/profile.html', context)


def leaderboard(request):
    players = AuthUser.objects.order_by('-level', '-current_experience')[:5]
    return render(request, 'user_profile/leaderboard.html', {'players': players})


@login_required
def my_games(request):
    user = request.user
    obj = Game.objects.all()
    games = [x for x in obj if str(user.pk) in x.players]
    context = {
        'user': user,
        'games': games,
    }
    return render(request, 'user_profile/games_list.html', context)

dnt/user_profile/templates/user_profile/friends.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    Список друзей:
{% endblock %}

{% block body %}
    {% include "main/includes/inc-info.html" %}

<h1>Список друзей</h1>
    <body>
    <table>
  <thead>
    <tr>
      <th>Никнейм</th>
      <th>Дата рождения</th>
      <th>Уровень игрока</th>
        <th>Email</th>
    </tr>
  </thead>
  <tbody>

        {% for friend in friends %}
      <tr>
        <td>{{ friend.username }}</td>
        <td>{{ friend.birthdate }}</td>
        <td>{{ friend.level }}</td>
        <td>{{ friend.email }}</td>
      </tr>

        {% empty %}
            <li>Вы не добавили еще ни одного друга</li>
        {% endfor %}
      </tbody>
</table>

<h3><a href="{% url 'user_profile:profile' pk=user.pk %}">Назад</a></h3>
{% endblock %}

dnt/user_profile/templates/user_profile/games_list.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    Мои игры
{% endblock %}

{% block body %}
    {% include "main/includes/inc-info.html" %}
    <h1>Мои игры:</h1>
    <table>
  <thead>
    <tr>
      <th>Тип игры</th>
      <th>Начало игры</th>
    </tr>
  </thead>
  <tbody>
  {% if games %}
        {% for game in games %}
        <tr>
            <td>{{ game.display_type }}</td>
            <td>{{ game.get_time }}</td>
      </tr>
      {% endfor %}
   </tbody>
</table>
  {% else %}
    <p>Игры не найдены.</p>
  {% endif %}
<h3><a href="{% url 'user_profile:profile' pk=user.pk %}">Назад</a></h3>
{% endblock %}

dnt/user_profile/templates/user_profile/leaderboard.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    Профиль
{% endblock %}

{% block body %}
    {% include "main/includes/inc-info.html" %}
    <table>
  <thead>
    <tr>
      <th>Никнейм</th>
      <th>Уровень игрока</th>
      <th>Опыт игрока</th>
    </tr>
  </thead>
  <tbody>
    {% for player in players %}
      <tr>
        <td>{{ player.username }}</td>
        <td>{{ player.level }}</td>
        <td>{{ player.current_experience }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
<h3><a href="{% url 'user_profile:profile' pk=user.pk %}">Назад</a></h3>
{% endblock %}

dnt/user_profile/templates/user_profile/manage_friends.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    Поиск друзей
{% endblock %}

{% block body %}
    {% include "main/includes/inc-info.html" %}
  <h1>Поиск друзей</h1>
  <form method="get">
    <input type="text" name="q" placeholder="Search for friends" value="{{ request.GET.q }}">
    <button type="submit">Поиск</button>
  </form>

  {% if results %}
    <ul>
      {% for friend in results %}
        <li>{{ friend.username }}
          {% if friend in user.friends.all %}
            <form method="post" action="{% url 'user_profile:search_friends' %}">
              {% csrf_token %}
              <input type="hidden" name="action" value="remove">
              <input type="hidden" name="friend_username" value="{{ friend.username }}">
              <button type="submit">Удалить из друзей</button>
            </form>
          {% else %}
            <form method="post" action="{% url 'user_profile:search_friends' %}">
              {% csrf_token %}
              <input type="hidden" name="action" value="add">
              <input type="hidden" name="friend_username" value="{{ friend.username }}">
              <button type="submit">Добавить в друзья</button>

            </form>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            {% if message.tags == "error" %}
                <li>{% if message.extra_tags %} class="{{ message.extra_tags }}"
        {% endif %}
                    {{ message }}
                </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endif %}
<h3><a href="{% url 'user_profile:profile' pk=user.pk %}">Назад</a></h3>
{% endblock %}

dnt/user_profile/templates/user_profile/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    Профиль
{% endblock %}

{% block body %}
    {% include "main/includes/inc-info.html" %}


<div class="container_auth" xmlns="http://www.w3.org/1999/html">

    <h1>Профиль игрока.</h1>
    {% if user.avatar %}
        <img src="{{ user.avatar.url }}" alt="" width="20%">
    {% else %}
        <img src="{{ DEFAULT_AVATAR_URL }}avatar_rMO7Sgc.jpg" alt="" width="20%">
    {% endif %}
    <h2 class="auth_h1">Ник: {{ user.username }}</h2>
    <h2 class="auth_h1">Дата рождения: {{ user.birthdate }}</h2>
    {% if user.email == '' %}
        <a href="{% url 'auth:edit' %}"><h3>Добавьте свой email</h3></a>
    {% else %}
    <h2 class="auth_h1">Email: {{ user.email }}</h2>
    {% endif %}
    <h2 class="auth_h1">Опыт текущего уровня: {{ user.current_experience }}</h2>
    <h2 class="auth_h1">Уровень: {{ user.level }}</h2>


</div>

<a href="{% url 'user_profile:leaderboard' %}"><h2>Пятёрка лидеров</h2></a>
 <a href="{% url 'user_profile:friends' %}" class="auth_link"><h2>Список друзей</h2></a>
<a href="{% url 'user_profile:search_friends' %}"><h2>Поиск друзей</h2></a>
<a href="{% url 'user_profile:games_list' %}"><h2>Мои игры</h2></a>
<a href="{% url 'auth:edit' %}"><h2>Редактировать профиль</h2></a>
{% endblock %}